import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Berichte & Analysen',
    'nav.dataCollection': 'Datensammlung',
    'nav.newsletterAdmin': 'Newsletter-Verwaltung',
    'nav.emailManagement': 'Email-Verwaltung',
    'nav.knowledgeBase': 'Wissensdatenbank',
    'nav.regulatoryUpdates': 'Regulatorische Updates',
    'nav.legalCases': 'Rechtsprechung',
    'nav.globalApprovals': 'Globale Zulassungen',
    'nav.ongoingApprovals': 'Laufende Zulassungen',
    'nav.intelligentSearch': 'Intelligente Suche',
    'nav.syncManager': 'Sync-Verwaltung',
    'nav.globalSources': 'Datenquellen-Verwaltung',
    'nav.newsletterManager': 'Newsletter Manager',
    'nav.historicalData': 'Historische Daten',
    'nav.customerManagement': 'Kunden-Management',
    'nav.userManagement': 'Benutzerverwaltung',
    'nav.systemAdmin': 'System-Verwaltung',
    'nav.auditLogs': 'Audit-Protokolle',
    
    // Navigation Sections
    'nav.sections.overview': 'ÜBERSICHT & STEUERUNG',
    'nav.sections.dataManagement': 'DATENMANAGEMENT',
    'nav.sections.compliance': 'COMPLIANCE & REGULIERUNG',
    'nav.sections.approvals': 'ZULASSUNGEN & REGISTRIERUNG',
    'nav.sections.advanced': 'ERWEITERT',
    
    // Search
    'search.askQuestion': 'Frage stellen...',
    
    // Status
    'status.label': 'Status',
    'status.online': 'Online',
    'status.dataSources': '46 Datenquellen',
    
    // Common
    'common.search': 'Suchen',
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Anzeigen',
    'common.download': 'Herunterladen',
    'common.export': 'Exportieren',
    'common.filter': 'Filter',
    'common.all': 'Alle',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.pending': 'Ausstehend',
    'common.completed': 'Abgeschlossen',
    'common.date': 'Datum',
    'common.status': 'Status',
    'common.priority': 'Priorität',
    'common.region': 'Region',
    'common.category': 'Kategorie',
    'common.source': 'Quelle',
    'common.language': 'Sprache',
    
    // Dashboard
    'dashboard.title': 'Regulatory Intelligence Dashboard',
    'dashboard.subtitle': 'KI-gestützte Analyse • Echtzeit-Updates • 100% Datenqualität',
    'dashboard.totalUpdates': 'Gesamt Updates',
    'dashboard.legalCases': 'Rechtsfälle',
    'dashboard.knowledgeArticles': 'Knowledge Articles',
    'dashboard.activeDataSources': 'Aktive Datenquellen',
    'dashboard.recentActivity': 'Aktuelle Aktivitäten',
    'dashboard.welcomeBack': 'Willkommen zurück',
    'dashboard.liveSystem': 'Live System',
    'dashboard.activeSourcesShort': '70 Quellen aktiv',
    'dashboard.updates': 'Updates',
    'dashboard.quality': 'Qualität',
    'dashboard.regulatoryUpdates': 'Regulatory Updates',
    'dashboard.regulatoryDescription': 'Neueste regulatorische Änderungen aus globalen Behörden',
    'dashboard.newsletterSources': 'Newsletter Sources',
    'dashboard.newsletterDescription': 'Authentische MedTech-Newsletter für automatische Inhaltsextraktion',
    'dashboard.noUpdates': 'Keine neuen Updates',
    'dashboard.autoSync': 'Updates werden automatisch synchronisiert',
    'dashboard.synchronization': 'Synchronisierung',
    'dashboard.active': 'Aktiv',
    
    // Intelligent Search
    'search.title': 'Intelligente Suche',
    'search.subtitle': 'KI-gestützte Suche durch alle Helix-Datenquellen',
    'search.placeholder': 'z.B. "MDR-Anforderungen für Klasse III Geräte"',
    'search.searching': 'Suche...',
    'search.results': 'Suchergebnisse',
    'search.aiAnswer': 'KI-Antwort',
    'search.noResults': 'Keine Ergebnisse gefunden',
    'search.confidence': 'Vertrauen',
    'search.relevance': 'Relevanz',
    'search.databaseResults': 'Eigene Daten',
    'search.aiResults': 'KI-Ergebnis',
    
    // Analytics
    'analytics.title': 'Analytics Intelligence',
    'analytics.subtitle': 'Umfassende Analyse der regulatorischen Datenlandschaft',
    'analytics.realTimeAnalytics': 'Echtzeit Analytics-Dashboard mit KI-gestützter Datenauswertung',
    'analytics.totalUpdates': 'Gesamt Updates',
    'analytics.pendingApprovals': 'Wartende Genehmigungen',
    'analytics.regionalDistribution': 'Regionale Verteilung',
    'analytics.categoryBreakdown': 'Kategorie Breakdown',
    'analytics.sourcePerformance': 'Datenquellen Performance',
    'analytics.dataQuality': 'Datenqualität',
    'analytics.syncStatus': 'Sync-Status',
    'analytics.activeConnections': 'Aktive Verbindungen',
    'analytics.processedToday': 'Heute verarbeitet',
    'analytics.trends': 'Trends & Entwicklungen',
    'analytics.currentMonth': 'Aktueller Monat',
    'analytics.increase': 'Anstieg',
    'analytics.systemHealth': 'System-Zustand',
    'analytics.optimal': 'Optimal',
    'analytics.allSystemsOperational': 'Alle Systeme betriebsbereit',
    'analytics.quickActions': 'Schnellaktionen',
    'analytics.refreshData': 'Daten aktualisieren',
    'analytics.exportReport': 'Bericht exportieren',
    'analytics.systemSettings': 'System-Einstellungen',
    'analytics.viewDetails': 'Details anzeigen',
    
    // Knowledge Base
    'knowledge.title': 'Wissensdatenbank',
    'knowledge.subtitle': 'Medizintechnik Wissensartikel aus authentischen Quellen',
    'knowledge.totalArticles': 'Gesamt Artikel',
    'knowledge.activeSources': 'Aktive Quellen',
    'knowledge.regions': 'Regionen',
    'knowledge.languages': 'Sprachen',
    'knowledge.searchPlaceholder': 'Nach Artikeln suchen...',
    
    // Newsletter Admin
    'newsletter.title': 'Newsletter Verwaltung',
    'newsletter.subtitle': 'Verwalten Sie authentische Newsletter-Quellen',
    'newsletter.addSource': 'Neue Quelle hinzufügen',
    'newsletter.configuredSources': 'Konfigurierte Newsletter-Quellen',
    'newsletter.authenticSources': 'Authentische Newsletter-Quellen',
    'newsletter.sourceSaved': 'Newsletter-Quelle gespeichert',
    'newsletter.sourceSavedDesc': 'Die Quelle wurde erfolgreich hinzugefügt/aktualisiert.',
    'newsletter.sourceSaveError': 'Die Newsletter-Quelle konnte nicht gespeichert werden.',
    'newsletter.sourceDeleted': 'Newsletter-Quelle gelöscht',
    'newsletter.sourceDeletedDesc': 'Die Quelle wurde erfolgreich entfernt.',
    'newsletter.testSuccess': 'Newsletter-Test erfolgreich',
    'newsletter.testFailed': 'Newsletter-Test fehlgeschlagen',
    'newsletter.testInProgress': 'Newsletter wird getestet...',
    'newsletter.connectionSuccess': 'Verbindung zur Newsletter-Quelle erfolgreich.',
    'newsletter.articlesFound': 'Artikel gefunden',
    'newsletter.connectionFailed': 'Verbindung zur Newsletter-Quelle konnte nicht hergestellt werden.',
    'newsletter.nameUrlRequired': 'Name und URL sind erforderlich.',
    'newsletter.configureSource': 'Newsletter-Quelle konfigurieren',
    'newsletter.configureSourceDesc': 'Fügen Sie eine neue authentische Newsletter-Quelle hinzu oder bearbeiten Sie eine bestehende.',
    'newsletter.namePlaceholder': 'z.B. MedTech Dive',
    'newsletter.selectCategory': 'Kategorie wählen',
    'newsletter.industryNewsletter': 'Branchen-Newsletter',
    'newsletter.regulatoryNewsletter': 'Regulatory Newsletter',
    'newsletter.websiteUrl': 'Website URL',
    'newsletter.urlPlaceholder': 'https://www.medtechdive.com/',
    'newsletter.rssFeedUrl': 'RSS Feed URL (optional)',
    'newsletter.rssPlaceholder': 'https://www.medtechdive.com/feeds/news/',
    'newsletter.description': 'Beschreibung',
    'newsletter.descriptionPlaceholder': 'Beschreibung der Newsletter-Quelle...',
    
    // Common expanded
    'common.name': 'Name',
    
    // Data Collection
    'dataCollection.title': 'Datensammlung',
    'dataCollection.subtitle': 'Zentrale Verwaltung aller Datenquellen und Sync-Prozesse',
    'dataCollection.activeSources': 'Aktive Quellen',
    'dataCollection.syncStatus': 'Sync-Status',
    'dataCollection.lastSync': 'Letzter Sync',
    'dataCollection.syncNow': 'Jetzt synchronisieren',
    'dataCollection.manageSource': 'Quelle verwalten',
    'dataCollection.newsletterSources': 'Newsletter-Quellen',
    'dataCollection.runningSyncs': 'Laufende Syncs',
    'dataCollection.pendingSyncs': 'Ausstehende Syncs',
    'dataCollection.recentSyncs': 'Kürzliche Syncs',
    
    // Regulatory Updates
    'regulatory.title': 'Regulatorische Updates',
    'regulatory.subtitle': 'Aktuelle Vorschriften und Richtlinien für Medizinprodukte',
    'regulatory.region': 'Region',
    'regulatory.authority': 'Behörde',
    'regulatory.deviceClass': 'Geräteklasse',
    'regulatory.published': 'Veröffentlicht',
    'regulatory.viewDetails': 'Details anzeigen',
    'regulatory.searchUpdates': 'Updates durchsuchen...',
    'regulatory.allRegions': 'Alle Regionen',
    'regulatory.allAuthorities': 'Alle Behörden',
    'regulatory.allCategories': 'Alle Kategorien',
    
    // Legal Cases
    'legal.title': 'Rechtsprechung',
    'legal.subtitle': 'Medizinrechtliche Fälle und Entscheidungen',
    'legal.court': 'Gericht',
    'legal.jurisdiction': 'Zuständigkeit',
    'legal.caseType': 'Falltyp',
    'legal.decision': 'Entscheidung',
    'legal.searchCases': 'Fälle durchsuchen...',
    'legal.viewCase': 'Fall anzeigen',
    
    // Buttons and Actions
    'action.viewAll': 'Alle anzeigen',
    'action.refresh': 'Aktualisieren',
    'action.configure': 'Konfigurieren',
    'action.test': 'Testen',
    'action.sync': 'Synchronisieren',
    'action.details': 'Details',
    'action.manage': 'Verwalten',
    'action.add': 'Hinzufügen',
    'action.remove': 'Entfernen',
    'action.update': 'Aktualisieren',
    'action.export': 'Export',
    
    // Knowledge Base specific
    'knowledge.noSummary': 'Keine Zusammenfassung verfügbar',
    'knowledge.fullContent': 'Vollständiger Inhalt',
    'knowledge.exportGenerated': 'Export generiert am',
    'search.summary': 'Zusammenfassung',
    
    // Time and Date
    'time.today': 'Heute',
    'time.yesterday': 'Gestern',
    'time.thisWeek': 'Diese Woche',
    'time.thisMonth': 'Dieser Monat',
    'time.lastMonth': 'Letzter Monat',
    'time.lastSync': 'Letzter Sync',
    'time.noSync': 'Noch kein Sync',
    'time.days': 'Tage',
    'time.year': 'Jahr',
    
    // Metrics and Statistics
    'metrics.total': 'Gesamt',
    'metrics.active': 'Aktiv',
    'metrics.pending': 'Ausstehend',
    'metrics.completed': 'Abgeschlossen',
    'metrics.failed': 'Fehlgeschlagen',
    'metrics.success': 'Erfolgreich',
    'metrics.trend': 'Trend',
    'metrics.increase': 'Anstieg',
    'metrics.decrease': 'Rückgang',
    'metrics.stable': 'Stabil',
    
    // Subscription Plans
    'basic.updates': 'Grundlegende Updates',
    'basic.notifications': 'Email-Benachrichtigungen',
    'basic.support': 'Standard-Support',
    'professional.analytics': 'Erweiterte Analytics',
    'professional.support': 'Priority Support',
    'professional.reports': 'Custom Reports',
    'professional.api': 'API Access',
    'enterprise.unlimited': 'Unbegrenzte Zugriffe',
    'enterprise.dedicated': 'Dedicated Account Manager',
    'enterprise.custom': 'Custom Integrations',
    
    // Authentication
    'auth.loginFailed': 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'auth.login': 'Anmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.demo': 'Demo-Zugang',
    
    // Access Control
    'access.restricted': 'Zugriff beschränkt',
    'access.noPermission': 'Keine Berechtigung',
    'access.contactAdmin': 'Kontaktieren Sie Ihren Administrator',
    
    // Customer Portal
    'customer.dashboard': 'Kunden-Dashboard',
    'customer.portal': 'Kundenportal',
    'customer.logout': 'Abmelden',
    'customer.chat': 'Support Chat',
    
    // Navigation Standards
    'nav.sections.standards': 'Standards & Normen',
    'nav.isoStandards': 'ISO Standards',
    
    // Extensions/Erweiterungen Page
    'extensions.title': 'Feedback & Anmerkungen',
    'extensions.subtitle': 'Zentrale Sammlung aller Benutzer-Anmerkungen und Verbesserungsvorschläge',
    'extensions.totalEntries': 'Gesamt: {count} Einträge',
    'extensions.new': 'Neu',
    'extensions.read': 'Gelesen',
    'extensions.discussed': 'Diskutiert',
    'extensions.implemented': 'Umgesetzt',
    'extensions.old': 'Alt (System)',
    'extensions.all': 'Alle',
    'extensions.newNotes': 'Neue Anmerkungen, die Ihre Aufmerksamkeit benötigen',
    'extensions.readNotes': 'Anmerkungen, die bereits gelesen wurden',
    'extensions.discussedNotes': 'Anmerkungen, die diskutiert wurden',
    'extensions.implementedNotes': 'Anmerkungen, die erfolgreich umgesetzt wurden',
    'extensions.oldNotes': 'Alte System-Stati (resolved/closed) - vor der neuen Kategorisierung',
    'extensions.allNotes': 'Vollständige Übersicht aller eingegangenen Anmerkungen',
    'extensions.perfect': 'Perfekt!',
    'extensions.allProcessed': 'Alle Anmerkungen wurden bearbeitet.',
    'extensions.noProcessed': 'Noch keine gelösten Anmerkungen',
    'extensions.feedbackAppears': 'Bearbeitete Anmerkungen erscheinen hier.',
    'extensions.noFeedback': 'Noch keine Anmerkungen',
    'extensions.feedbackWillAppear': 'Feedback von Benutzern wird hier angezeigt.',
    'extensions.readButton': 'Gelesen ✓',
    'extensions.discussedButton': 'Diskutiert ✓',
    'extensions.implementedButton': 'Umgesetzt ✓',
    'extensions.delete': 'Löschen',
    'extensions.confirmDelete': 'Möchten Sie dieses Feedback wirklich löschen?',
    'extensions.dataSourcesOverview': 'Datenquellen-Übersicht',
    'extensions.completeMapping': 'Komplette Zuordnung aller Datenquellen zu den jeweiligen Plattform-Bereichen',
    'extensions.regulatoryUpdates': 'Regulatory Updates ({count} Einträge)',
    'extensions.knowledgeContent': 'Knowledge & Content ({count} Einträge)',
    'extensions.legalCases': 'Legal Cases ({count} Einträge)',
    'extensions.technicalSystemData': 'Technische & System-Daten ({count} Einträge)',
    'extensions.totalDataStock': 'Gesamt-Datenbestand',
    'extensions.totalRecords': 'Datensätze gesamt',
    'extensions.databaseTables': 'Datenbank-Tabellen',
    'extensions.transmissionRate': 'Übertragungsrate',
    'extensions.apiEndpoints': 'API-Endpunkte',
    'extensions.moreDiscovered': '{count} mehr entdeckt!',
    'extensions.allCaptured': 'Alle erfasst ✓',
    'extensions.complete': 'Vollständig ✓',
    'extensions.allActive': 'Alle aktiv ✓',
    'extensions.corrected': '✅ KORRIGIERT: Alle Datenquellen vollständig ausgeschöpft',
    'extensions.realTimeTracking': 'Real-time Tracking, Live User-Aktivität',
    'extensions.systemTables': 'Multi-Tenant-Architektur, Benutzer-Management',
    
    // User Management
    'userManagement.title': 'Benutzerverwaltung',
    'userManagement.subtitle': 'Verwalten Sie Benutzer, Rollen und Berechtigungen',
    'userManagement.newUser': 'Neuer Benutzer',
    'userManagement.createUser': 'Neuen Benutzer erstellen',
    'userManagement.createDescription': 'Erstellen Sie ein neues Benutzerkonto mit entsprechenden Berechtigungen.',
    'userManagement.firstName': 'Vorname',
    'userManagement.lastName': 'Nachname',
    'userManagement.email': 'E-Mail',
    'userManagement.role': 'Rolle',
    'userManagement.permissions': 'Berechtigungen',
    'userManagement.userCreated': 'Benutzer erstellt',
    'userManagement.userCreatedDesc': 'Der neue Benutzer wurde erfolgreich erstellt.',
    'userManagement.userUpdated': 'Benutzer aktualisiert',
    'userManagement.userUpdatedDesc': 'Die Benutzerdaten wurden erfolgreich aktualisiert.',
    'userManagement.userDeleted': 'Benutzer gelöscht',
    'userManagement.userDeletedDesc': 'Der Benutzer wurde erfolgreich gelöscht.',
    'userManagement.createError': 'Benutzer konnte nicht erstellt werden.',
    'userManagement.updateError': 'Benutzer konnte nicht aktualisiert werden.',
    'userManagement.deleteError': 'Benutzer konnte nicht gelöscht werden.',
    
    // Form validation
    'validation.invalidEmail': 'Ungültige E-Mail-Adresse',
    'validation.firstNameRequired': 'Vorname erforderlich',
    'validation.lastNameRequired': 'Nachname erforderlich',
    
    // Permissions
    'permissions.read': 'Lesen',
    'permissions.readDesc': 'Daten anzeigen und lesen',
    'permissions.write': 'Schreiben',
    'permissions.writeDesc': 'Daten erstellen und bearbeiten',
    'permissions.delete': 'Löschen',
    'permissions.deleteDesc': 'Daten löschen',
    'permissions.approve': 'Genehmigen',
    'permissions.approveDesc': 'Inhalte genehmigen oder ablehnen',
    'permissions.admin': 'Administration',
    'permissions.adminDesc': 'Vollzugriff auf alle Funktionen',
    'permissions.userManagement': 'Benutzerverwaltung',
    'permissions.userManagementDesc': 'Benutzer verwalten',
    
    // Save button states
    'button.save': 'Speichern',
    'button.saving': 'Speichere...',
    'button.create': 'Erstellen',
    'button.creating': 'Erstelle...',
    
    // Mobile Navigation
    'mobile.mainModules': 'Hauptmodule',
    'mobile.knowledgeBase': 'Wissensbasis',
    'mobile.administration': 'Verwaltung',
    'mobile.approvalWorkflow': 'Genehmigungsverfahren',
    'mobile.aiInsights': 'KI-Erkenntnisse',
    'mobile.customKnowledge': 'Benutzerdefiniertes Wissen',
    'mobile.historicalData': 'Historische Daten',
    'mobile.legalCases': 'Rechtsfälle',
    'mobile.dataSourcesAdmin': 'Datenquellen-Admin',
    'mobile.auditLogs': 'Audit-Protokolle',
    
    // Branding and Footer
    'branding.appName': 'MedTech Intelligence',
    'branding.platformVersion': 'Helix Platform v2.0',
    'branding.copyright': '© 2025 MedTech Intelligence',
    
    // User Management - Extended
    'userManagement.tabs.users': 'Benutzer',
    'userManagement.tabs.activity': 'Aktivitäten',
    'userManagement.tabs.permissions': 'Berechtigungen',
    'userManagement.allUsers': 'Alle Benutzer',
    'userManagement.allUsersDesc': 'Übersicht über alle registrierten Benutzer im System',
    'userManagement.searchUsers': 'Benutzer suchen...',
    'userManagement.allRoles': 'Alle Rollen',
    'userManagement.userColumn': 'Benutzer',
    'userManagement.roleColumn': 'Rolle',
    'userManagement.statusColumn': 'Status',
    'userManagement.lastLoginColumn': 'Letzter Login',
    'userManagement.createdColumn': 'Erstellt',
    'userManagement.actionsColumn': 'Aktionen',
    'userManagement.never': 'Nie',
    'userManagement.userActivities': 'Benutzeraktivitäten',
    'userManagement.userActivitiesDesc': 'Letzte Aktivitäten und Aktionen der Benutzer',
    'userManagement.userLabel': 'Benutzer:',
    'userManagement.managePermissions': 'Berechtigungen verwalten',
    'userManagement.managePermissionsDesc': 'Übersicht über verfügbare Berechtigungen im System',
    'userManagement.activeSwitch': 'Aktiv',
    'userManagement.activeSwitchDesc': 'Benutzer kann sich anmelden',
    
    // User Roles
    'roles.user': 'Benutzer',
    'roles.reviewer': 'Reviewer', 
    'roles.admin': 'Administrator',
    
    // Date formatting
    'time.never': 'Nie',
    
    // Email Management
    'email.title': 'E-Mail-Verwaltung',
    'email.subtitle': 'Gmail-Integration für Kundenbenachrichtigungen',
    'email.testConnection': 'Gmail testen',
    'email.testing': 'Teste...',
    'email.connectionSuccess': '✅ Gmail-Verbindung erfolgreich',
    'email.connectionSuccessDesc': 'E-Mail-Provider funktioniert einwandfrei',
    'email.connectionFailed': '❌ Gmail-Verbindung fehlgeschlagen',
    'email.connectionError': 'Verbindungsfehler',
    'email.testFailed': '❌ Test fehlgeschlagen',
    'email.testFailedDesc': 'Gmail benötigt App-Passwort für 2FA',
    'email.testEmailSent': '✅ Test-E-Mail versendet',
    'email.testEmailSentDesc': 'E-Mail erfolgreich an {email} gesendet',
    'email.sendFailed': '❌ Versand fehlgeschlagen',
    'email.sendFailedDesc': 'Fehler beim Versenden der Test-E-Mail',
    'email.emailRequired': 'E-Mail-Adresse erforderlich',
    'email.emailRequiredDesc': 'Bitte geben Sie eine E-Mail-Adresse ein',
    'email.loading': 'Gmail-Integration wird geladen...',
    'email.providers': 'E-Mail-Provider',
    'email.templates': 'E-Mail-Templates',
    'email.statistics': 'Statistiken',
    'email.gmailProvider': 'Gmail-Provider (deltawayshelixinfo@gmail.com)',
    'email.gmailConfig': 'Gmail SMTP-Konfiguration für E-Mail-Versand',
    'email.noProviders': 'Keine E-Mail-Provider konfiguriert.',
    'email.user': 'Benutzer:',
    'email.dailyLimit': 'Tageslimit:',
    'email.sentToday': 'Heute versendet:',
    'email.security': 'Sicherheit:',
    'email.appPasswordRequired': 'App-Passwort erforderlich',
    'email.appPasswordDesc': 'deltawayshelixinfo@gmail.com benötigt ein App-Passwort für die 2-Faktor-Authentifizierung.',
    'email.stepsTitle': 'Schritte:',
    'email.step1': 'Google-Konto → Sicherheit → 2-Faktor-Authentifizierung',
    'email.step2': 'App-Passwörter generieren',
    'email.step3': 'Neues App-Passwort für "Helix Email" erstellen',
    'email.step4': '16-stelliges Passwort in Server-Konfiguration einsetzen',
    'email.templatesTitle': 'E-Mail-Templates',
    'email.templatesDesc': 'Professionelle E-Mail-Vorlagen für verschiedene Kundeninteraktionen',
    'email.templateType': 'Typ:',
    'email.customerDataTitle': 'Kundendaten für Test-E-Mail:',
    'email.customer': 'Kunde:',
    'email.plan': 'Plan:',
    'email.dashboardUrl': 'Dashboard URL:',
    'email.loginUrl': 'Login URL:',
    'email.amount': 'Betrag:',
    'email.sendWithData': 'E-Mail mit konfigurierten Daten senden',
    'email.totalSent': 'Gesamt versendet',
    'email.delivered': 'Zugestellt',
    'email.failed': 'Fehlgeschlagen',
    'email.subscribers': 'Abonnenten',
    'email.overview': 'E-Mail-Übersicht',
    'email.overviewDesc': 'Aktuelle Performance-Metriken',
    'email.sentTodayLabel': 'Heute versendet:',
    'email.weeklyDigest': 'Weekly Digest Abonnenten:',
    'email.instantAlerts': 'Instant Alert Abonnenten:',
    'email.lastSent': 'Letzte E-Mail versendet:'
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Reports & Analytics',
    'nav.dataCollection': 'Data Collection',
    'nav.newsletterAdmin': 'Newsletter Management',
    'nav.emailManagement': 'Email Management',
    'nav.knowledgeBase': 'Knowledge Base',
    'nav.regulatoryUpdates': 'Regulatory Updates',
    'nav.legalCases': 'Legal Cases',
    'nav.globalApprovals': 'Global Approvals',
    'nav.ongoingApprovals': 'Ongoing Approvals',
    'nav.intelligentSearch': 'Intelligent Search',
    'nav.syncManager': 'Sync Management',
    'nav.globalSources': 'Data Source Management',
    'nav.newsletterManager': 'Newsletter Manager',
    'nav.historicalData': 'Historical Data',
    'nav.customerManagement': 'Customer Management',
    'nav.userManagement': 'User Management',
    'nav.systemAdmin': 'System Administration',
    'nav.auditLogs': 'Audit Logs',
    
    // Navigation Sections
    'nav.sections.overview': 'OVERVIEW & CONTROL',
    'nav.sections.dataManagement': 'DATA MANAGEMENT',
    'nav.sections.compliance': 'COMPLIANCE & REGULATION',
    'nav.sections.approvals': 'APPROVALS & REGISTRATION',
    'nav.sections.advanced': 'ADVANCED',
    
    // Search
    'search.askQuestion': 'Ask a question...',
    
    // Status
    'status.label': 'Status',
    'status.online': 'Online',
    'status.dataSources': '46 Data Sources',
    
    // Common
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.region': 'Region',
    'common.category': 'Category',
    'common.source': 'Source',
    'common.language': 'Language',
    
    // Dashboard
    'dashboard.title': 'Regulatory Intelligence Dashboard',
    'dashboard.subtitle': 'AI-powered Analysis • Real-time Updates • 100% Data Quality',
    'dashboard.totalUpdates': 'Total Updates',
    'dashboard.legalCases': 'Legal Cases',
    'dashboard.knowledgeArticles': 'Knowledge Articles',
    'dashboard.activeDataSources': 'Active Data Sources',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.welcomeBack': 'Welcome Back',
    'dashboard.liveSystem': 'Live System',
    'dashboard.activeSourcesShort': '70 Sources Active',
    'dashboard.updates': 'Updates',
    'dashboard.quality': 'Quality',
    'dashboard.regulatoryUpdates': 'Regulatory Updates',
    'dashboard.regulatoryDescription': 'Latest regulatory changes from global authorities',
    'dashboard.newsletterSources': 'Newsletter Sources',
    'dashboard.newsletterDescription': 'Authentic MedTech newsletters for automatic content extraction',
    'dashboard.noUpdates': 'No new updates',
    'dashboard.autoSync': 'Updates are automatically synchronized',
    'dashboard.synchronization': 'Synchronization',
    'dashboard.active': 'Active',
    
    // Intelligent Search
    'search.title': 'Intelligent Search',
    'search.subtitle': 'AI-powered search across all Helix data sources',
    'search.placeholder': 'e.g. "MDR requirements for Class III devices"',
    'search.searching': 'Searching...',
    'search.results': 'Search Results',
    'search.aiAnswer': 'AI Answer',
    'search.noResults': 'No results found',
    'search.confidence': 'Confidence',
    'search.relevance': 'Relevance',
    'search.databaseResults': 'Database Results',
    'search.aiResults': 'AI Results',
    
    // Analytics
    'analytics.title': 'Analytics Intelligence',
    'analytics.subtitle': 'Comprehensive analysis of regulatory data landscape',
    'analytics.realTimeAnalytics': 'Real-time analytics dashboard with AI-powered data analysis',
    'analytics.totalUpdates': 'Total Updates',
    'analytics.pendingApprovals': 'Pending Approvals',
    'analytics.regionalDistribution': 'Regional Distribution',
    'analytics.categoryBreakdown': 'Category Breakdown',
    'analytics.sourcePerformance': 'Data Sources Performance',
    'analytics.dataQuality': 'Data Quality',
    'analytics.syncStatus': 'Sync Status',
    'analytics.activeConnections': 'Active Connections',
    'analytics.processedToday': 'Processed Today',
    'analytics.trends': 'Trends & Developments',
    'analytics.currentMonth': 'Current Month',
    'analytics.increase': 'Increase',
    'analytics.systemHealth': 'System Health',
    'analytics.optimal': 'Optimal',
    'analytics.allSystemsOperational': 'All systems operational',
    'analytics.quickActions': 'Quick Actions',
    'analytics.refreshData': 'Refresh Data',
    'analytics.exportReport': 'Export Report',
    'analytics.systemSettings': 'System Settings',
    'analytics.viewDetails': 'View Details',
    
    // Knowledge Base
    'knowledge.title': 'Knowledge Base',
    'knowledge.subtitle': 'Medical device knowledge articles from authentic sources',
    'knowledge.totalArticles': 'Total Articles',
    'knowledge.activeSources': 'Active Sources',
    'knowledge.regions': 'Regions',
    'knowledge.languages': 'Languages',
    'knowledge.searchPlaceholder': 'Search for articles...',
    
    // Newsletter Admin
    'newsletter.title': 'Newsletter Administration',
    'newsletter.subtitle': 'Manage authentic newsletter sources',
    'newsletter.addSource': 'Add New Source',
    'newsletter.configuredSources': 'Configured Newsletter Sources',
    'newsletter.authenticSources': 'Authentic Newsletter Sources',
    'newsletter.sourceSaved': 'Newsletter source saved',
    'newsletter.sourceSavedDesc': 'The source has been successfully added/updated.',
    'newsletter.sourceSaveError': 'The newsletter source could not be saved.',
    'newsletter.sourceDeleted': 'Newsletter source deleted',
    'newsletter.sourceDeletedDesc': 'The source has been successfully removed.',
    'newsletter.testSuccess': 'Newsletter test successful',
    'newsletter.testFailed': 'Newsletter test failed',
    'newsletter.testInProgress': 'Testing newsletter...',
    'newsletter.connectionSuccess': 'Connection to newsletter source successful.',
    'newsletter.articlesFound': 'articles found',
    'newsletter.connectionFailed': 'Connection to newsletter source could not be established.',
    'newsletter.nameUrlRequired': 'Name and URL are required.',
    'newsletter.configureSource': 'Configure Newsletter Source',
    'newsletter.configureSourceDesc': 'Add a new authentic newsletter source or edit an existing one.',
    'newsletter.namePlaceholder': 'e.g. MedTech Dive',
    'newsletter.selectCategory': 'Select category',
    'newsletter.industryNewsletter': 'Industry Newsletter',
    'newsletter.regulatoryNewsletter': 'Regulatory Newsletter',
    'newsletter.websiteUrl': 'Website URL',
    'newsletter.urlPlaceholder': 'https://www.medtechdive.com/',
    'newsletter.rssFeedUrl': 'RSS Feed URL (optional)',
    'newsletter.rssPlaceholder': 'https://www.medtechdive.com/feeds/news/',
    'newsletter.description': 'Description',
    'newsletter.descriptionPlaceholder': 'Description of the newsletter source...',
    
    // Common expanded
    'common.name': 'Name',
    
    // Data Collection
    'dataCollection.title': 'Data Collection',
    'dataCollection.subtitle': 'Central management of all data sources and sync processes',
    'dataCollection.activeSources': 'Active Sources',
    'dataCollection.syncStatus': 'Sync Status',
    'dataCollection.lastSync': 'Last Sync',
    'dataCollection.syncNow': 'Sync Now',
    'dataCollection.manageSource': 'Manage Source',
    'dataCollection.newsletterSources': 'Newsletter Sources',
    'dataCollection.runningSyncs': 'Running Syncs',
    'dataCollection.pendingSyncs': 'Pending Syncs',
    'dataCollection.recentSyncs': 'Recent Syncs',
    
    // Regulatory Updates
    'regulatory.title': 'Regulatory Updates',
    'regulatory.subtitle': 'Current regulations and guidelines for medical devices',
    'regulatory.region': 'Region',
    'regulatory.authority': 'Authority',
    'regulatory.deviceClass': 'Device Class',
    'regulatory.published': 'Published',
    'regulatory.viewDetails': 'View Details',
    'regulatory.searchUpdates': 'Search updates...',
    'regulatory.allRegions': 'All Regions',
    'regulatory.allAuthorities': 'All Authorities',
    'regulatory.allCategories': 'All Categories',
    
    // Legal Cases
    'legal.title': 'Legal Cases',
    'legal.subtitle': 'Medical law cases and decisions',
    'legal.court': 'Court',
    'legal.jurisdiction': 'Jurisdiction',
    'legal.caseType': 'Case Type',
    'legal.decision': 'Decision',
    'legal.searchCases': 'Search cases...',
    'legal.viewCase': 'View Case',
    
    // Buttons and Actions
    'action.viewAll': 'View All',
    'action.refresh': 'Refresh',
    'action.configure': 'Configure',
    'action.test': 'Test',
    'action.sync': 'Sync',
    'action.details': 'Details',
    'action.manage': 'Manage',
    'action.add': 'Add',
    'action.remove': 'Remove',
    'action.update': 'Update',
    'action.export': 'Export',
    
    // Knowledge Base specific
    'knowledge.noSummary': 'No summary available',
    'knowledge.fullContent': 'Full Content',
    'knowledge.exportGenerated': 'Export generated on',
    'search.summary': 'Summary',
    
    // Time and Date
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This Week',
    'time.thisMonth': 'This Month',
    'time.lastMonth': 'Last Month',
    'time.lastSync': 'Last Sync',
    'time.noSync': 'No Sync Yet',
    'time.days': 'Days',
    'time.year': 'Year',
    
    // Metrics and Statistics
    'metrics.total': 'Total',
    'metrics.active': 'Active',
    'metrics.pending': 'Pending',
    'metrics.completed': 'Completed',
    'metrics.failed': 'Failed',
    'metrics.success': 'Successful',
    'metrics.trend': 'Trend',
    'metrics.increase': 'Increase',
    'metrics.decrease': 'Decrease',
    'metrics.stable': 'Stable',
    
    // Subscription Plans
    'basic.updates': 'Basic Updates',
    'basic.notifications': 'Email Notifications',
    'basic.support': 'Standard Support',
    'professional.analytics': 'Advanced Analytics',
    'professional.support': 'Priority Support',
    'professional.reports': 'Custom Reports',
    'professional.api': 'API Access',
    'enterprise.unlimited': 'Unlimited Access',
    'enterprise.dedicated': 'Dedicated Account Manager',
    'enterprise.custom': 'Custom Integrations',
    
    // Authentication
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.demo': 'Demo Access',
    
    // Access Control
    'access.restricted': 'Zugriff beschränkt',
    'access.noPermission': 'Keine Berechtigung',
    'access.contactAdmin': 'Wenden Sie sich an Ihren Administrator',
    
    // Customer Portal
    'customer.dashboard': 'Kunden-Dashboard',
    'customer.portal': 'Kunden-Portal',
    'customer.logout': 'Abmelden',
    'customer.chat': 'Support Chat',
    
    // AI Insights
    'ai.insights': 'KI-Einblicke',
    'ai.executiveBriefing': 'Executive Briefing (Gemini KI)',
    'ai.documentAnalysis': 'Dokumentanalyse (Gemini KI)',
    'ai.analyzing': 'Analysiere...',
    'ai.startAnalysis': 'KI-Analyse starten',
    'ai.textRequired': 'Text erforderlich',
    'ai.enterText': 'Bitte geben Sie einen Text zur Analyse ein.',
    'ai.analysisError': 'Fehler bei der Analyse',
    'ai.analysisCompleted': '✨ KI-Analyse abgeschlossen',
    'ai.analysisSuccess': 'Die Analyse wurde erfolgreich durchgeführt.',
    'ai.enterTextPlaceholder': 'Fügen Sie hier den Text ein, der analysiert werden soll...',
    'ai.summary': 'Zusammenfassung',
    'ai.keyPoints': 'Wichtige Punkte',
    'ai.complianceRequirements': 'Compliance-Anforderungen',
    'ai.confidence': 'Vertrauen',
    'ai.sentimentAnalysis': 'Sentiment-Analyse',
    'ai.complianceInsights': 'Compliance-Erkenntnisse',
    'ai.legalCaseSummary': 'Rechtsfallzusammenfassung',
    
    // Navigation Standards
    'nav.sections.standards': 'Standards & Norms',
    'nav.isoStandards': 'ISO Standards',
    
    // Extensions/Erweiterungen Page
    'extensions.title': 'Feedback & Comments',
    'extensions.subtitle': 'Central collection of all user comments and improvement suggestions',
    'extensions.totalEntries': 'Total: {count} entries',
    'extensions.new': 'New',
    'extensions.read': 'Read',
    'extensions.discussed': 'Discussed',
    'extensions.implemented': 'Implemented',
    'extensions.old': 'Old (System)',
    'extensions.all': 'All',
    'extensions.newNotes': 'New comments that need your attention',
    'extensions.readNotes': 'Comments that have already been read',
    'extensions.discussedNotes': 'Comments that have been discussed',
    'extensions.implementedNotes': 'Comments that have been successfully implemented',
    'extensions.oldNotes': 'Old system status (resolved/closed) - before new categorization',
    'extensions.allNotes': 'Complete overview of all received comments',
    'extensions.perfect': 'Perfect!',
    'extensions.allProcessed': 'All comments have been processed.',
    'extensions.noProcessed': 'No resolved comments yet',
    'extensions.feedbackAppears': 'Processed comments appear here.',
    'extensions.noFeedback': 'No comments yet',
    'extensions.feedbackWillAppear': 'User feedback will be displayed here.',
    'extensions.readButton': 'Read ✓',
    'extensions.discussedButton': 'Discussed ✓',
    'extensions.implementedButton': 'Implemented ✓',
    'extensions.delete': 'Delete',
    'extensions.confirmDelete': 'Do you really want to delete this feedback?',
    'extensions.dataSourcesOverview': 'Data Sources Overview',
    'extensions.completeMapping': 'Complete mapping of all data sources to respective platform areas',
    'extensions.regulatoryUpdates': 'Regulatory Updates ({count} entries)',
    'extensions.knowledgeContent': 'Knowledge & Content ({count} entries)',
    'extensions.legalCases': 'Legal Cases ({count} entries)',
    'extensions.technicalSystemData': 'Technical & System Data ({count} entries)',
    'extensions.totalDataStock': 'Total Data Stock',
    'extensions.totalRecords': 'Total records',
    'extensions.databaseTables': 'Database tables',
    'extensions.transmissionRate': 'Transmission rate',
    'extensions.apiEndpoints': 'API endpoints',
    'extensions.moreDiscovered': '{count} more discovered!',
    'extensions.allCaptured': 'All captured ✓',
    'extensions.complete': 'Complete ✓',
    'extensions.allActive': 'All active ✓',
    'extensions.corrected': '✅ CORRECTED: All data sources fully utilized',
    'extensions.realTimeTracking': 'Real-time tracking, live user activity',
    'extensions.systemTables': 'Multi-tenant architecture, user management',
    
    // User Management
    'userManagement.title': 'User Management',
    'userManagement.subtitle': 'Manage users, roles and permissions',
    'userManagement.newUser': 'New User',
    'userManagement.createUser': 'Create New User',
    'userManagement.createDescription': 'Create a new user account with appropriate permissions.',
    'userManagement.firstName': 'First Name',
    'userManagement.lastName': 'Last Name',
    'userManagement.email': 'Email',
    'userManagement.role': 'Role',
    'userManagement.permissions': 'Permissions',
    'userManagement.userCreated': 'User Created',
    'userManagement.userCreatedDesc': 'The new user has been successfully created.',
    'userManagement.userUpdated': 'User Updated',
    'userManagement.userUpdatedDesc': 'The user data has been successfully updated.',
    'userManagement.userDeleted': 'User Deleted',
    'userManagement.userDeletedDesc': 'The user has been successfully deleted.',
    'userManagement.createError': 'User could not be created.',
    'userManagement.updateError': 'User could not be updated.',
    'userManagement.deleteError': 'User could not be deleted.',
    
    // Form validation
    'validation.invalidEmail': 'Invalid email address',
    'validation.firstNameRequired': 'First name required',
    'validation.lastNameRequired': 'Last name required',
    
    // Permissions
    'permissions.read': 'Read',
    'permissions.readDesc': 'View and read data',
    'permissions.write': 'Write',
    'permissions.writeDesc': 'Create and edit data',
    'permissions.delete': 'Delete',
    'permissions.deleteDesc': 'Delete data',
    'permissions.approve': 'Approve',
    'permissions.approveDesc': 'Approve or reject content',
    'permissions.admin': 'Administration',
    'permissions.adminDesc': 'Full access to all functions',
    'permissions.userManagement': 'User Management',
    'permissions.userManagementDesc': 'Manage users',
    
    // Save button states
    'button.save': 'Save',
    'button.saving': 'Saving...',
    'button.create': 'Create',
    'button.creating': 'Creating...',
    
    // Mobile Navigation
    'mobile.mainModules': 'Main Modules',
    'mobile.knowledgeBase': 'Knowledge Base',
    'mobile.administration': 'Administration',
    'mobile.approvalWorkflow': 'Approval Workflow',
    'mobile.aiInsights': 'AI Insights',
    'mobile.customKnowledge': 'Custom Knowledge',
    'mobile.historicalData': 'Historical Data',
    'mobile.legalCases': 'Legal Cases',
    'mobile.dataSourcesAdmin': 'Data Sources Admin',
    'mobile.auditLogs': 'Audit Logs',
    
    // Branding and Footer
    'branding.appName': 'MedTech Intelligence',
    'branding.platformVersion': 'Helix Platform v2.0',
    'branding.copyright': '© 2025 MedTech Intelligence',
    
    // User Management - Extended
    'userManagement.tabs.users': 'Users',
    'userManagement.tabs.activity': 'Activity',
    'userManagement.tabs.permissions': 'Permissions',
    'userManagement.allUsers': 'All Users',
    'userManagement.allUsersDesc': 'Overview of all registered users in the system',
    'userManagement.searchUsers': 'Search users...',
    'userManagement.allRoles': 'All Roles',
    'userManagement.userColumn': 'User',
    'userManagement.roleColumn': 'Role',
    'userManagement.statusColumn': 'Status',
    'userManagement.lastLoginColumn': 'Last Login',
    'userManagement.createdColumn': 'Created',
    'userManagement.actionsColumn': 'Actions',
    'userManagement.never': 'Never',
    'userManagement.userActivities': 'User Activities',
    'userManagement.userActivitiesDesc': 'Recent activities and actions by users',
    'userManagement.userLabel': 'User:',
    'userManagement.managePermissions': 'Manage Permissions',
    'userManagement.managePermissionsDesc': 'Overview of available permissions in the system',
    'userManagement.activeSwitch': 'Active',
    'userManagement.activeSwitchDesc': 'User can log in',
    
    // User Roles
    'roles.user': 'User',
    'roles.reviewer': 'Reviewer',
    'roles.admin': 'Administrator',
    
    // Date formatting
    'time.never': 'Never',
    
    // Email Management
    'email.title': 'Email Management',
    'email.subtitle': 'Gmail integration for customer notifications',
    'email.testConnection': 'Test Gmail',
    'email.testing': 'Testing...',
    'email.connectionSuccess': '✅ Gmail connection successful',
    'email.connectionSuccessDesc': 'Email provider is working perfectly',
    'email.connectionFailed': '❌ Gmail connection failed',
    'email.connectionError': 'Connection error',
    'email.testFailed': '❌ Test failed',
    'email.testFailedDesc': 'Gmail requires app password for 2FA',
    'email.testEmailSent': '✅ Test email sent',
    'email.testEmailSentDesc': 'Email successfully sent to {email}',
    'email.sendFailed': '❌ Send failed',
    'email.sendFailedDesc': 'Error sending test email',
    'email.emailRequired': 'Email address required',
    'email.emailRequiredDesc': 'Please enter an email address',
    'email.loading': 'Gmail integration loading...',
    'email.providers': 'Email Providers',
    'email.templates': 'Email Templates',
    'email.statistics': 'Statistics',
    'email.gmailProvider': 'Gmail Provider (deltawayshelixinfo@gmail.com)',
    'email.gmailConfig': 'Gmail SMTP configuration for email sending',
    'email.noProviders': 'No email providers configured.',
    'email.user': 'User:',
    'email.dailyLimit': 'Daily limit:',
    'email.sentToday': 'Sent today:',
    'email.security': 'Security:',
    'email.appPasswordRequired': 'App password required',
    'email.appPasswordDesc': 'deltawayshelixinfo@gmail.com requires an app password for 2-factor authentication.',
    'email.stepsTitle': 'Steps:',
    'email.step1': 'Google Account → Security → 2-Factor Authentication',
    'email.step2': 'Generate app passwords',
    'email.step3': 'Create new app password for "Helix Email"',
    'email.step4': 'Insert 16-digit password into server configuration',
    'email.templatesTitle': 'Email Templates',
    'email.templatesDesc': 'Professional email templates for various customer interactions',
    'email.templateType': 'Type:',
    'email.customerDataTitle': 'Customer data for test email:',
    'email.customer': 'Customer:',
    'email.plan': 'Plan:',
    'email.dashboardUrl': 'Dashboard URL:',
    'email.loginUrl': 'Login URL:',
    'email.amount': 'Amount:',
    'email.sendWithData': 'Send email with configured data',
    'email.totalSent': 'Total sent',
    'email.delivered': 'Delivered',
    'email.failed': 'Failed',
    'email.subscribers': 'Subscribers',
    'email.overview': 'Email Overview',
    'email.overviewDesc': 'Current performance metrics',
    'email.sentTodayLabel': 'Sent today:',
    'email.weeklyDigest': 'Weekly digest subscribers:',
    'email.instantAlerts': 'Instant alert subscribers:',
    'email.lastSent': 'Last email sent:'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('helix-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('helix-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}